### ISSUE TITLE
Hangs on loading

### ISSUE THREAD

**Issue by Sezyrrith** [KevConrad/GaiaPyCreator#2]
Okay, downloaded and started messing with this today on Win10. 
First issue, was getting an error on line 42 of View_MenuBar.py when opening a rom file, the wildcard format wasn't parsing. It only let me load .sfc files, even though .smc files should be listed as openable, and would immediately error out upon attempting to load. Changing that line to:
`wildcard = "Illusion of Gaia ROM file (*.sfc)|*.sfc|Illusion of Gaia ROM file (*.smc)|*.smc",`
made it load (then had to change what's now lines 52 and 64 similarly, removing the last | symbol - I'm not sure if this is a Windows only issue, or what, as the site where I found this fix indicated this was a quirk of win32).

However, while I could now create a new project and load the rom file properly, it just hangs after that.

I'd also like to note that it kinda spams the command prompt window, 5x repeats of status each time something succeeds. i.e.:
```
PUBSUB: Done sending message of topic "project_save"
PUBSUB: Done sending message of topic "project_save"
PUBSUB: Done sending message of topic "project_save"
PUBSUB: Done sending message of topic "project_save"
PUBSUB: Done sending message of topic "project_save"
```

This happens for every status change, progress bar increase, and so on. There are only a few apparent exceptions:
`decompSize: 0x2000`
and the one time it comes up differently,
```
decompSize: 0x702f
'bool' dtypes must have a length of 1, but received a length of 0.
```
as well as
`Initialized all objects`
Those messages happen one time only each cycle.

I tried closing and reopening, then loading the project file, which did not save under the intended filename, but "Project.json" instead, and it hangs in the same way. Program becomes entirely unresponsive, no error messages in the command prompt window.

**Comment by KevConrad** [comment]
Hi @Sezyrrith thanks for the information and the fix.

I included your fix in commit b62a6231a85955d7de573c8fd9fe4a653a8d7eb1

The hangup is also fixed by disabling a progress bar which seem to make problems on windows...
